apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  POSTGRES_DB: {{ .Chart.Name }}
  POSTGRES_USER: {{ .Chart.Name }}
  POSTGRES_PASSWORD: {{ .Chart.Name }}
  POSTGRES_HOST: {{ .Chart.Name }}-ingress  
  POSTGRES_PORT: "5432"