apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ingress
  labels:
    app: {{ .Chart.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 5432
  selector:
    app: {{ .Chart.Name }}
