apiVersion: v1
kind: Service
metadata:
  name: device-manager-svc
  labels:
    app: device-manager
spec:
  type: {{ .Values.service.type }}
  selector:
    app: device-manager
  ports:
  - port: {{ .Values.service.port }}

