apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: 2048Mi
          limits:
            memory: 2048Mi
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_REDIS_HOST
          value: redis-master
        - name: SPRING_REDIS_PORT
          value: "6379"
        - name: JDK_JAVA_OPTIONS
          value: -Xms256m -Xmx256m
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-ingress:5432/postgres
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: shtech-kafka-cm-envars
              key: KAFKA_BOOTSTRAP
        - name: SPRING_DATA_CASSANDRA_CONTACT_POINTS
          value: shtech-cass-cl-shtech-cass-dc-service.cass-operator
        - name: SPRING_DATA_CASSANDRA_KEYSPACE_NAME
          value: shtech
        - name: SPRING_DATA_CASSANDRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: shtech-cass-cl-superuser
              key: username
        - name: SPRING_DATA_CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shtech-cass-cl-superuser
              key: password
      imagePullSecrets:
      - name: shtech.azurecr.io 