{{- range .Values.processors }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-{{ . }}
spec:
  selector:
    matchLabels:
      app: processor-{{ . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: processor-{{ . }}
    spec:
      imagePullSecrets:
      - name: shtech.azurecr.io
      containers:
      - name: processor
        image: shtech.azurecr.io/receiver:latest
        imagePullPolicy: Always
        command: ["python"]
        args: ["shtech/processor.py"]
        env:
        - name: PROCESSOR_TOPICS
          value: ^sensor_report_{{ . }}
        - name: KAFKA_BOOTSTRAP
          valueFrom:
            configMapKeyRef:
              name: shtech-kafka-cm-envars
              key: KAFKA_BOOTSTRAP
        - name: KAFKA_AUTH_TYPE
          value: NONE
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef: 
              name: postgres-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef: 
              name: postgres-config
              key: POSTGRES_PORT
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef: 
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom: 
            configMapKeyRef: 
              name: postgres-config
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          valueFrom: 
            configMapKeyRef: 
              name: postgres-config
              key: POSTGRES_DB
        - name: CASSANDRA_HOST
          value: shtech-cass-cl-shtech-cass-dc-service.cass-operator
        - name: CASSANDRA_PORT
          value: "9092"
        - name: CASSANDRA_USERNAME
          valueFrom:
            secretKeyRef:
              name: shtech-cass-cl-superuser
              key: username
        - name: CASSANDRA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shtech-cass-cl-superuser
              key: pass
        - name: REDIS_HOST
          value: redis-master
        - name: REDIS_PORT
          value: ""
---
{{- end }}