apiVersion: v2
name: main
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: postgres
  version: 0.1.0
  enabled: true
  repository: file://../postgres
- name: redis
  version: 0.1.0
  enabled: true
  repository: file://../redis
- name: data-lake-connector
  version: 0.1.0
  enabled: true
  repository: file://../data-lake-connector
- name: device-manager
  version: 0.1.0
  enabled: true
  repository: file://../device-manager
- name: frontend
  version: 0.1.0
  enabled: true
  repository: file://../frontend
- name: icomox-kafka-connect
  version: 0.1.0
  enabled: true
  repository: file://../icomox-kafka-connect
- name: keycloak
  version: 0.1.0
  enabled: true
  repository: file://../keycloak
- name: processors
  version: 0.1.0
  enabled: true
  repository: file://../processors
- name: receiver
  version: 0.1.0
  enabled: true
  repository: file://../receiver
- name: rest-service
  version: 0.1.0
  enabled: true
  repository: file://../rest-service