apiVersion: v1
kind: Service
metadata:
  name: rest-service-svc
  labels:
    app: rest-backend
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: rest-backend
