apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master 
  labels:
    app: {{ .Chart.Name }}    
spec:
  selector:
    matchLabels:     
      app: {{ .Chart.Name }}
      role: master
      tier: backend
  replicas: {{ .Values.replicaCount }}       
  template:          
    metadata:
      labels:        
        app: {{ .Chart.Name }}
        role: master
        tier: backend
    spec:            
      containers:
      - name: {{ .Chart.Name }}
        image: shtechthirdparty.azurecr.io/redis:1.3
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6325