apiVersion: v1
kind: Service        
metadata:
  name: redis-master 
  labels:            
    app: {{ .Chart.Name }}
    role: master
    tier: backend
spec:
  ports:
  - port: {{ .Values.service.port }}       
    targetPort: {{ .Values.service.port }}
  selector:          
    app: {{ .Chart.Name }}
    role: master
    tier: backend